baseURL = 'https://website-29s.pages.dev'
languageCode = 'en-us'
title = 'Huzef UR Rahman'


[params]
    defaultTheme = "auto" 
    disableThemeToggle = false
    ShowCodeCopyButtons = true
    ShowReadingTime = false
    ShowPostNavLinks = false
    ShowShareButtons = false
    ShowBreadCrumbs = false
    hideFooter = false
    showFullTextinRoot = false
    description = "Materials and Design Engineer."
    logoImage = "logo_bl.png"      # The default Black logo
    logoImageDark = "logo_wh.png"  # The White logo for dark themes
    # This specifically removes the "Powered by" lines in PaperMod
    disableFingerprinting = true

  [[menu.main]]
    name = "About"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Writings"
    url = "/posts/"
    identifier = "posts"
    weight = 20
[[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    identifier = "thoughts"
    weight = 30
[[menu.main]]
    name = "Miscellany"
    url = "/misc/"
    identifier = "misc"
    weight = 40
