baseURL = 'https://website-29s.pages.dev'
languageCode = 'en-us'
title = 'Huzef UR Rahman'
theme = "PaperMod"

[params]
    title = "Huzef UR Rahman"
    defaultTheme = "auto" 
    disableThemeToggle = false
    ShowCodeCopyButtons = true
    ShowReadingTime = false
    ShowPostNavLinks = false
    ShowShareButtons = false
    ShowBreadCrumbs = false

    [params.profileMode]
        enabled = true
        title = "Huzef UR Rahman"
        subtitle = "Materials and Design Engineer. (Add more of your bio here)"
        # imageUrl = "https://website-29s.pages.dev/images/avatar.png" # Uncomment when you have an image

[[menu.main]]
    name = "About"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Writings"
    url = "/posts/"
    weight = 20
[[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 30
[[menu.main]]
    name = "Miscellany"
    url = "/misc/"
    weight = 40
